### PR TITLE
Minorbugfixes

### PR DESCRIPTION
**Pull request by paras-B**
Hi Ian,

property downloaded_tables in api_class.py fails to validate the path. so, i made the changes for linux and windows file system. tested it on both OS and works fine. Also, added pandas errors parameter to be 'ignore' because the REF_DATE format for this "13-10-0805-02" in Issue #7 has a format of ['2015/2016'] as in example. so, thought if we put in a errors='ignore' in pd.to_datetime. it will just pass the dataframe and REF_DATE will be returned as object instead of datetime but will be left for user of library, how they want to further use the dataframe. instead of throwing errors. i tested for "13-10-0805-02" parse dates doesn't fail, after making the changes.

### CODE REVIEW

**Comment by ianepreston** [comment]
Hi Paras,

Thanks for submitting this! Looks like the build failed, but it also looks like it was just a StatsCan web api outage. I'm re running the build. I want to take some time to review the code before I merge and I'm pretty booked up right now, so please be patient on the merge.

**Comment by ianepreston** [comment]
Hi @paras-B. You were on the right track with the downloaded tables fix, but the issue arose in the init if download path was passed as a string. Pathlib has an operator overloading on ```/``` so you can use it to join path objects in a cross platform way. See my updated commit for an implementation that resolves the issue. 

It looks like I have a few tests still failing on this branch. They don't seem to be related to your changes, I think the StatsCan api just changed or something. I'm still going to resolve them before I merge this branch. 

After I've got that sorted I'll take a look at your fix for issue 7. 

Finally, I'm also going to do a version bump so when this merges I can build an updated package.

**Comment by paras-B** [comment]
Thanks for looking into this.
And Thanks for letting me know about operator overloading, will check and test. you can check when you get time, fix for issue 7. it just parameter added (errors='ignore'), i think its good just to pass the data because if the API doesn't return date column in appropriate format. then pd.to_datetime() throws error.
 Also, just a question. do you know why build keeps on failing. i also ran the build on the forked repo but it failed. I am quite new with CI. if you can just guide me to right direction. i will try to fix it.  Thanks.

**Comment by ianepreston** [comment]
I'm almost done fixing the existing test errors. It looks like the web data service is returning lists in a different order. Kind of annoying. I'm either fixing the order, or where I remember calling my comparison on sorted versions of the lists. Should be able to push those commits soon and then I'll try and look at #7 later today

**Comment by ianepreston** [comment]
@paras-B you can see why the build failed by loading up the CI console and clicking on the failed build. But as a shortcut I can just tell you it failed because some of my tests were failing. You can run pytest on your local copy of the repo and get the same failures.

**Comment by ianepreston** [comment]
OK, all tests are passing locally. I found one other spot in the codebase that used ```to_datetime``` and fixed it up too. I ended up removing the whole try except block. Passing in the date format string makes it parse a little faster, but increases the risk it won't load at all for someone. I'd rather return back a datetime a little slower, or a string column, over an error. The build keeps failing on Travis due to connectivity issues. I'll try rerunning it in the morning and merge and close the issue.

**Pull request merged**
